service: notification-service
frameworkVersion: '3'

provider:
  iam:
    role:
      statements:
        - ${file(./iam/SendMailIAM.yml):SendMailIAM}
  memorySize: 256
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
