service: auction-service
frameworkVersion: '3'

provider:
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
  iam:
    role:
      statements:
        - ${file(./iam/AuctionsTableIAM.yml):AuctionsTableIAM}
        - ${file(./iam/MailQueueIAM.yml):MailQueueIAM}
  memorySize: 256
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    AuctionsTable: ${file(./resources/AuctionsTable.yml):AuctionsTable}
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: false
            type: token
            identitySource: method.request.header.Authorization
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: false
            type: token
            identitySource: method.request.header.Authorization
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: false
            type: token
            identitySource: method.request.header.Authorization
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: false
            type: token
            identitySource: method.request.header.Authorization
  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    #   - schedule: rate(1 minute)

custom:
  authorizer: arn:aws:lambda:${aws:region}:${aws:accountId}:function:auth-service-${sls:stage}-auth
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  MailQueue:
    arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
